### ISSUE TITLE
remove graphs for removed files

### ISSUE THREAD

**Issue by retog** [plazi/turtle-hook#1]
This query shows a graph for a file that doesn't exist.

```
SELECT * WHERE {
graph <https://raw.githubusercontent.com/plazi/treatments-rdf/main/data/03/D2/AB/03D2AB06FFCE5139F8EC2395DCE9E30A> 
   {
      ?s ?p ?o .
   }
}
```

**Comment by retog** [comment]
@nleanba : I hoped this would have been fixed with the refactoring, but the graph is still there. Should we delete all graphs and make a full update?

**Comment by nleanba** [comment]
I feel like this is the only real option. However, if we are going to replace all graphs, I think we should use that moment to change the graph uris to some that actually go somewhere (I suggest `https://treatment.plazi.org/id/...`)

**Comment by nleanba** [comment]
Currently, this full update is running. While it is running, https://treatment.ld.plazi.org/sparql only has a partial dataset (slowly growing). After the update is complete, it should have a full, correct, current dataset without any old/wrong graphs.
