### ISSUE TITLE
Accept Webhooks properly if pervious is still being handled

### ISSUE THREAD

**Issue by nleanba** [plazi/turtle-hook#2]
Currently, it seems that it doesn't acknowledge incoming web hooks if it is still busy handling a previous one, leading to the proxy (traefik?) to report a 504.

This makes it hard to distinguish between a web hook that did not arrive and one that just didnt get acknowledged.

- The actual processing should be moved to a worker, so the main thread can respond instantly to incoming web hooks and acknowledge them
- It is possible to respond using a Stream, such that the acknowledgement can be sent instantly while the logging is provided afterwards in the same response; we should make use of that (https://docs.deno.com/runtime/manual/runtime/http_server_apis#responding-with-a-response)

**Comment by retog** [comment]
I don't think the second works, as github would probably close the connection.

**Comment by nleanba** [comment]
if github closes the connection there isn't much we can do; it is at worst no change to status quo.
